name: Publish multi-arch Docker images

on:
    push:
        branches:
            - main
            - dev
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set Release Tag
              run: |
                  if [ "${GITHUB_REF#refs/*/}" = "main" ]; \
                  then echo "RELEASE_TAG=latest"; \
                  elif [ "${GITHUB_REF#refs/*/}" = "dev" ]; \
                  then echo "RELEASE_TAG=dev"; \
                  else echo "RELEASE_TAG=${GITHUB_REF#refs/*/}"; fi \
                  >> $GITHUB_ENV
            - uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - uses: docker/setup-buildx-action@v2
              id: buildx
            - uses: docker/build-push-action@v3
              with:
                  context: .
                  file: Dockerfile
                  platforms: linux/arm64, linux/amd64, linux/arm/v7, linux/386, linux/arm/v6
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/crypto-db:${RELEASE_TAG}
