name: Publish multi-arch Docker images

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

jobs:
  release:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/crypto-db
          flavor: |
            suffix=${{ matrix.tag }},onlatest=true
          tags: |
            type=edge,branch=dev,suffix=-dev
            type=edge,branch=main,suffix=${{ matrix.tag }}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
